.TH lector\-previewer 1 2007\-01\-15  
.SH NAME
lector\-previewer \- show print preview for a document
.SH SYNOPSIS
\fBlector\-previewer\fR \fB[file]\fR 
.SH DESCRIPTION
lector\-previewer is a MATE program to
show print preview dialog for files supported by lector.
.SH OPTIONS
lector\-previewer obeys all normal GTK+ 
command line options.
.SH "SEE ALSO"
\fBlector\fR(1),
\fBgtk\-options\fR(7).
.PP
https://cafe-desktop.org/
