##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/lector
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gettext
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libcaja-extension-dev
    - libdjvulibre-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgxps-dev
    - libkpathsea-dev
    - libsynctex-dev
    - libtool
    - libpoppler-glib-dev
    - libsecret-1-dev
    - libsm-dev
    - libspectre-dev
    - libtiff-dev
    - libx11-dev
    - libxml2-dev
    - lsb-release
    - make
    - xsltproc
    - yelp-tools
    - zlib1g-dev

    #required for cafe-common
    - autoconf

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev libcail-3-dev'
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum --enable-cxx-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/lector/raw/master/data/icons/16x16/apps/lector.png; fi
