##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/atril
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - gobject-introspection
    - libcaja-extension-dev
    - libdjvulibre-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgxps-dev
    - libkpathsea-dev
    - libsynctex-dev
    - libpoppler-glib-dev
    - libsecret-1-dev
    - libsm-dev
    - libspectre-dev
    - libtiff-dev
    - libwebkit2gtk-4.0-dev
    - libx11-dev
    - libxml2-dev
    - lsb-release
    - make
    - mate-common
    - xsltproc
    - yelp-tools
    - zlib1g-dev

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum --enable-cxx-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/atril/raw/master/data/icons/16x16/apps/atril.png; fi
