##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/atril
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - gobject-introspection
    - libcaja-extension-dev
    - libdjvulibre-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgxps-dev
    - libkpathsea-dev
    - libsynctex-dev
    - libpoppler-glib-dev
    - libsecret-1-dev
    - libsm-dev
    - libspectre-dev
    - libtiff-dev
    - libwebkit2gtk-4.0-dev
    - libx11-dev
    - libxml2-dev
    - lsb-release
    - make
    - mate-common
    - xsltproc
    - yelp-tools
    - zlib1g-dev

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     egrep -lRZ 'G_GNUC_BEGIN_IGNORE_DEPRECATIONS' . | xargs -0 -l sed -i -e 's/G_GNUC_BEGIN_IGNORE_DEPRECATIONS/ /g'
  -     egrep -lRZ 'G_GNUC_END_IGNORE_DEPRECATIONS' . | xargs -0 -l sed -i -e 's/G_GNUC_END_IGNORE_DEPRECATIONS/ /g'
  - fi

build_scripts:
  - ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude --force -D__cplusplus .
  - fi

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude --force -D__cplusplus .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/atril/raw/master/data/icons/16x16/apps/atril.png
  - fi
  - make distcheck
