.TH lector\-thumbnailer 1 2007\-01\-15  
.SH NAME
lector\-thumbnailer \- create png thumbnails from lector supported documents
.SH SYNOPSIS
\fBlector\-thumbnailer\fR [\-s \fBsize\fR] \fBinput\fR \fBoutput\fR 
.SH DESCRIPTION
lector\-thumbnailer is a CAFE program to
create thumbnails from files supported by lector.
.SH OPTIONS
lector\-thumbnailer obeys all normal GTK+ 
command line options. The only option \-s \fIsize
\fRmakes it possible to choose the vertical size
of the created thumbnail.
.SH "SEE ALSO"
\fBlector\fR(1),
\fBgtk\-options\fR(7).
.PP
https://cafe-desktop.org//
